variables:
  AZURE_STATE_FILE_STORAGE: terraformbucket
  AZURE_LOCATION: germanywestcentral
  AZURE_RESOURCE_GROUP: storage-resource-group

stages:
  - initial-setup
  - terraform-plan
  - terraform-deploy

create-statefile-bucket:
  image: mcr.microsoft.com/azure-cli
  stage: initial-setup
  script:
    - echo "---------------- STATEFILE CREATING ----------------"
    - az login --service-principal --username $AZURE_APP_ID --password $AZURE_PASSWORD --tenant $AZURE_TENANT
    - echo "🔍️ Checking if $AZURE_STATE_FILE_STORAGE exists"
    - |
      if az storage account show --name $AZURE_STATE_FILE_STORAGE --resource-group $AZURE_RESOURCE_GROUP &> /dev/null; then
        echo "✨ $AZURE_STATE_FILE_STORAGE already exists"
      else
        echo "🔧 The statefile bucket does not exist. Creating..."
        az storage account create --name $AZURE_STATE_FILE_STORAGE --resource-group $AZURE_RESOURCE_GROUP --location $AZURE_LOCATION --sku Standard_RAGRS --kind StorageV2 --allow-blob-public-access false
      fi
  only:
    - main

terraform-plan:
  stage: terraform-plan
  script:
    - echo planing....

terraform-deploy:
  stage: terraform-deploy
  script:
    - echo deploying....