variables:
  STATE_FILE_STORAGE: terraformbucket
  LOCATION: germanywestcentral

stages:
  - initial-setup
  - terraform-plan
  - terraform-deploy

create-statefile-bucket:
  image: mcr.microsoft.com/azure-cli
  stage: initial-setup
  script:
    - echo "Generate the Terraform statefile bucket '$STATE_FILE_STORAGE' if it does not exist"
    - az login --service-principal --username $AZURE_APP_ID --password $AZURE_PASSWORD --tenant $AZURE_TENANT
    - az storage account create --name $STATE_FILE_STORAGE --resource-group storage-resource-group --location $LOCATION --sku Standard_RAGRS --kind StorageV2 --allow-blob-public-access false
  only:
    - main

terraform-plan:
  stage: terraform-plan
  script:
    - echo planing....

terraform-deploy:
  stage: terraform-deploy
  script:
    - echo deploying....