variables:
  STATE_FILE_STORAGE: yuyatinnfeld-dev-bucket-12322
  LOCATION: germany

stages:
  - init
  - plan
  - deploy

init:
  image: mcr.microsoft.com/azure-cli
  stage: create-statefile-bucket
  script:
    - echo "Generate the Terraform statefile bucket '$STATE_FILE_STORAGE' if it does not exist"
    - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT
    - az storage account create --name $STATE_FILE_STORAGE --resource-group storage-resource-group --location $LOCATION --sku Standard_RAGRS --kind StorageV2 --allow-blob-public-access false
  only:
    - main

plan:
  stage: terraform-plan
  script:
    - echo planing....

deploy:
  stage: terraform-apply
  script:
    - echo deploying....