variables:
  REPO_NAME: test-repo
  APP_NAME: test-app

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo building....

test:
  stage: test
  script:
    - echo testing....

deploy:
  image: mcr.microsoft.com/azure-cli
  stage: deploy
  script:
    - echo deploying....
    - az account list