variables:
  AZURE_LOCATION: germanywestcentral
  CONTAINER_NAME: tfstate

stages:
  - initial-setup
  - terraform-plan
  - terraform-deploy

############################ create statefile bucket ############################

# .create-statefile-bucket:
#   image: mcr.microsoft.com/azure-cli
#   stage: initial-setup
#   script:
#     - echo "🔍️ Checking if $AZURE_STATE_FILE_STORAGE exists"
#     - |
#       if az storage account show --name $AZURE_STATE_FILE_STORAGE --resource-group $AZURE_RESOURCE_GROUP &> /dev/null; then
#         echo "✨ $AZURE_STATE_FILE_STORAGE already exists"
#       else
#         echo "🔧 The statefile bucket does not exist. Creating"
#         # Create resource group
#         az group create --name $AZURE_RESOURCE_GROUP --location $AZURE_LOCATION
#         # Create storage account
#         az storage account create --name $AZURE_STATE_FILE_STORAGE --resource-group $AZURE_RESOURCE_GROUP --location $AZURE_LOCATION --sku Standard_RAGRS --kind StorageV2 --allow-blob-public-access false
#         # Create blob container
#         az storage container create --name $CONTAINER_NAME --account-name $AZURE_STATE_FILE_STORAGE
#       fi

create-statefile-bucket-dev:
  image: mcr.microsoft.com/azure-cli
  stage: initial-setup
  before_script:
    - az login --service-principal --username $AZURE_APP_ID_DEV --password $AZURE_PASSWORD_DEV --tenant $AZURE_TENANT_DEV 
  script:
    - echo "🔍️ Checking if $AZURE_STATE_FILE_STORAGE exists"
    - |
      if az storage account show --name $AZURE_STATE_FILE_STORAGE --resource-group $AZURE_RESOURCE_GROUP &> /dev/null; then
        echo "✨ $AZURE_STATE_FILE_STORAGE already exists"
      else
        echo "🔧 The statefile bucket does not exist. Creating"
        # Create resource group
        az group create --name $AZURE_RESOURCE_GROUP --location $AZURE_LOCATION
        # Create storage account
        az storage account create --name $AZURE_STATE_FILE_STORAGE --resource-group $AZURE_RESOURCE_GROUP --location $AZURE_LOCATION --sku Standard_RAGRS --kind StorageV2 --allow-blob-public-access false
        # Create blob container
        az storage container create --name $CONTAINER_NAME --account-name $AZURE_STATE_FILE_STORAGE
      fi
  variables:
    AZURE_STATE_FILE_STORAGE: terraformdev
    AZURE_RESOURCE_GROUP: storage-resource-group-dev
  only: 
    - develop

############################ show terraform resources ############################

terraform-plan-dev:
  stage: terraform-plan
  script:
    - echo planing....
    - echo terraform apply -vars-file terraform.tfvars

############################ create terraform resources ############################

terraform-deploy-dev:
  stage: terraform-deploy
  script:
    - echo deploying....